### ISSUE TITLE
\let\pdftracingfonts\tracingfonts

### ISSUE THREAD

**Issue by schlcht** [josephwright/luatex85#1]
\pdftracingfonts has been renamed to \tracingfonts 
(It's not mentioned in the CHANGES, but in the manual, "Changes from pdftex")
Note that this conflicts with the tracefnt package...

**Comment by davidcarlisle** [comment]
Thanks for the comment, I guess safest would be to add

`\directlua{tex.enableprimitives('pdf',{'tracingfonts'})}`

to define \pdftracingfonts whether or not \tracingfonts has the primitive definition or a latex format or tracefint definition.

**Comment by davidcarlisle** [comment]
\pdftracingfonts now defined in version submitted to ctan
