### ISSUE TITLE
How to compile

### ISSUE THREAD

**Issue by adaldo** [josephwright/luatex85#3]
Sorry if it sounds noob-ish, but could you please explain how compile the files in this repo to obtain a `luatex.sty`?

**Comment by josephwright** [comment]
There's nothing here that makes `luatex.sty`: you can do `tex luatex85.ins` to get `luatex85.sty` out of `luatex.dtx`.

**Comment by josephwright** [comment]
Normally you really shouldn't need to do this!

**Comment by adaldo** [comment]
Thanks! The first one worked, so now I have a `luatex85.sty`. On the second one: do you mean that I can just clone the repo in a location visible to my `lulatex` compiler?

**Comment by josephwright** [comment]
No, I mean that almost all users get `luatex85` and indeed everything else TeX-related from their TeX system: you really shouldn't need to download it directly. What TeX system do you have (_e.g._ what does `pdftex --version` at the Command Line say)?

**Comment by adaldo** [comment]
If I `pdftex --version` I get

`pdfTeX 3.1415926-2.5-1.40.14 (TeX Live 2013/Debian)
kpathsea version 6.1.1
Copyright 2013 Peter Breitenlohner (eTeX)/Han The Thanh (pdfTeX).
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Peter Breitenlohner (eTeX)/Han The Thanh (pdfTeX).
Compiled with libpng 1.2.49; using libpng 1.2.50
Compiled with zlib 1.2.8; using zlib 1.2.8
Compiled with poppler version 0.24.5
`

**Comment by josephwright** [comment]
OK, you have TL2013 so why do you need `luatex85`? This is needed to address issues that come from the LuaTeX version in TL16 (and is to aid the transition, not a permanent solution).

**Comment by adaldo** [comment]
I want to compile a beamer where I use a `tikzlibrary` called `graphdrawing`. To use this library I need to compile with `lualatex`, so I do `lualatex my_awesome_beamer.tex`. This returns me the following complaint

`
! Undefined control sequence.
\checkfont #1^^@-\suppressfontnotfounderror 
                                          =1\font \x = "#1" at 10pt \selectf...
l.91 }
`

So I looked it up, and in some stackexchange thread (I can give you the link, if I manage to find it again), somebody said "try `\RequirePackage{luatex85}` ".

**Comment by davidcarlisle** [comment]
you should not believe everything you read on the internet:-) luatex85.sty
will do nothing at all on old luatex.

But in general luatex is a fast changing engine which is being developed
and so has many changes in commands each year. While it is possible to use
tex or pdftex distributions from  decades ago with few problems, if you are
using luatex really you should update your tex system to texlive 2016, many
luatex fragments that you find will not work with older luatex
implementations.

David

**Comment by josephwright** [comment]
What @davidcarlisle  says :-) In this case, you are using code that's been updated for newer macro approaches. What you want is

```
\directlua{
  tex.enableprimitives("",tex.extraprimitives("luatex"))
}
```

at the start of your file.

However, note that LuaTeX is still very much in development. For reasons of realism, most package authors target only the current release, so the one in TeX Live 2016. You will face issues with older LuaTeX versions for this reason.

**Comment by adaldo** [comment]
Ok so here is our happy ending.

The `\directlua` fix works, but it clashes with `\tikzlibrary{external}`. My terminal tells me that I have to `pdflatex -shell-escape my_awesome_beamer.tex`. This does not work, but since I am using `lualatex` I get all smart and `lualatex -shell-escape my_awesome_beamer.tex`. This works fine and I can also see that after the first compile it gets all faster thanks to the exetrnalize.

Thank you all for your help!
